# see config options in https://github.com/vzhong/wrangl/wrangl/conf
defaults:
  - wrangl_supervised_experiment
  - _self_

early_stopping:
    monitor: 'val_acc'
    mode: 'max'

model: 'mymodel'
project: 'wrangle-example-xor-clf'

dhid: 300
