# see config options in https://github.com/vzhong/wrangl/wrangl/conf
defaults:
  - wrangl_supervised_experiment
  - _self_

##########
# training
##########
early_stopping:
    monitor: 'val_acc'
    mode: 'max'
optim:
  params:
    lr: 0.00001
devices: 0
batch_size: 100
collate_fn: 'ignore'  # use 'ignore' to pass an identity collate and define featurize instead
max_steps: 1_000
log_every_n_steps: 100
val_check_interval: 0.5
val_sample_size: 100
ftrain: '${oc.env:PWD}/data/dynasent-v1.1-round01-yelp-train.jsonl'
feval: '${oc.env:PWD}/data/dynasent-v1.1-round01-yelp-dev.jsonl'
lm: bert-base-uncased


##########
# naming
##########
model: 'mymodel'
project: 'wrangl-examples-dynasent_clf'
