name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install -e .[dev]
    - name: Build docs
      run: |
        env WRANGL_DOCS_HOST=https://github.com/vzhong/wrangl/blob/main/wrangl/ wdocs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
