name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install CPU pytorch
      run: |
        pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Install package
      run: |
        pip install -e .[dev]
    - name: Run tests
      run: |
        python -m wrangl.interactive.cmd autotest
    - name: Build docs
      run: |
        WRANGL_DOCS_HOST=https://github.com/r2llab/wrangl/blob/main/wrangl/ python -m wrangl.interactive.cmd autodoc
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} publish_dir: ./docs/build
